### ISSUE TITLE
Two server instances

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#15]
Sometimes when the server restart, it will boot up with two instances, I am not sure why.

**Comment by quarantin** [comment]
I need more info to be able to reproduce the issue. Can you give more context? For example are you performing a manual restart, or are you talking about automatic restart because of a daily restart? Or because a mod was updated? Can you provide console output with the two instances running? Also the log files in `/var/log/pzst` and in `/home/pzserver/.pzst/pzst.log` could help.

**Comment by Lu5ck** [comment]
this is an on and off occurrence
iirc, all occurrences happen after daily restart

i can only determine two instances are running via `top` while console is outputting one instance of db error
i also remember doing `kill -9 <id>` which doesn't effectively kill the instances as new instances will pop up to replace them, only doing several times to finally kill them

there were mods update restart after that which does not have the same problem
then the subsequent daily restart resulted the same two instances which I finally do a `reboot`

atm, i am not running pzupdate cron
