### ISSUE TITLE
clearzpop doesn't remove zombies, it reset zombies

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#16]
As topic

**Comment by Lu5ck** [comment]
No, that's not how it is. You delete the bin file responsible for recording the zombies details of different cell. The game will check the files for the zombies if a player is within range of those cells. If the file does not exist, the game will simply recreate the file with the largest possible amount of zombies as according to servertest_SandboxVars.

It is basically akin to a soft reset but in this case, resetting zombies across the map back to its original peak state. Pretty much opposite of "clearing" zombie, very misleading.

**Comment by quarantin** [comment]
The target goal is to clear zombies in cells where there's no player, to alleviate the server because sometimes you visit areas with an insane amount of zombies, especially on servers that have been running for months with no hard reset and no players in these areas to clear the zombie population. What are you suggesting?

**Comment by Lu5ck** [comment]
I am saying deleting the zpop bin file does not clear the zombies, it simply reset the zombies count to the original state. Why not you try it to understand what I am saying.
