### ISSUE TITLE
Clearing server

### ISSUE THREAD

**Issue by smithers54** [quarantin/pz-server-tools#2]
Does this have a tool for clearing the server completely? I'm trying to get everything set back to day 1.

**Comment by quarantin** [comment]
Assuming you installed your pzserver with pzst, you'd have to run this for each pzserver user:
```pzserver uninstall```
and then from pzstadmin user:
```pzst uninstall```
You'd still have your ~/Zomboid folder though.
Otherwise it all depends where you installed the game server.
If you really want to start fresh, why not reinstalling the whole operating system?

**Comment by smithers54** [comment]
Thanks! I wound up deleting the servertest directory and that did the trick. Another question, Are saves backed up automatically at restart and where are they stored? I'm going to start backing my saves up to the cloud.

**Comment by quarantin** [comment]
Every time the server stops, restarts or crash, the save is backed-up to ~/Zomboid/Backups if the server process terminated correctly, or to ~/Zomboid/Backups.unsafe in case it didn't terminate correctly.
