### ISSUE TITLE
Daily auto restart doesn't seem to be working

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#7]
I checked crontab, it seems to be there
`* * * * * pzupdate`

I checked the /etc/pzst/config.json on both pzstadmin and pzserver1 too
Also used pzst checkconfig command.
`
{
        "daily-restarts": [
                "03:00",
                "09:00",
                "15:00",
                "21:00"
        ],
        "editor": "nano",
        "max-backups": 5,
        "pzservers": [
                "pzserver1"
        ],
        "restart-sequence": [
                10,
                5,
                2,
                1
        ],
        "user": "pzstadmin",
        "install": "/home/pzstadmin/pz-server-tools"
}
`

What am I missing?
Some kind of permissions?

**Comment by quarantin** [comment]
I just had a look, it seems the cron file is not deployed when installing pz-server-tools. Until I fix this issue, if you really need this feature you can simply copy the cron file to `/etc/cron.d/`
As pzstadmin user, run the following commands:
```cd $HOME```
```sudo cp cron/pzserver /etc/cron.d/```
My users only rely on the restart from mod updates, which seem to be enough since no one complained so far :sweat_smile:

**Comment by quarantin** [comment]
Thanks for the report, I'll check if I can reproduce the issue.

**Comment by Lu5ck** [comment]
If I run the pzupdate command manually, it works.

What is this **${LOCALLOG}** file? Maybe we can learn something from there?

**Comment by quarantin** [comment]
I just fixed this issue thanks to your input. Sorry for the long delay, I've been quite busy with other stuff and thank you for your patience.
